// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP_COVID19.ORM;

namespace TP_COVID19.ORM.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210211180356_Bug-Fix")]
    partial class BugFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("TP_COVID19.Web.Models.Patient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Sexe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Personnes");
                });

            modelBuilder.Entity("TP_COVID19.Web.Models.Vaccin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Vaccins");
                });

            modelBuilder.Entity("TP_COVID19.Web.Models.Vaccination", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PatientID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VaccinID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("PatientID");

                    b.HasIndex("VaccinID");

                    b.ToTable("Vaccinations");
                });

            modelBuilder.Entity("TP_COVID19.Web.Models.Vaccination", b =>
                {
                    b.HasOne("TP_COVID19.Web.Models.Patient", null)
                        .WithMany("Vaccinations")
                        .HasForeignKey("PatientID");

                    b.HasOne("TP_COVID19.Web.Models.Vaccin", null)
                        .WithMany("Vaccinations")
                        .HasForeignKey("VaccinID");
                });

            modelBuilder.Entity("TP_COVID19.Web.Models.Patient", b =>
                {
                    b.Navigation("Vaccinations");
                });

            modelBuilder.Entity("TP_COVID19.Web.Models.Vaccin", b =>
                {
                    b.Navigation("Vaccinations");
                });
#pragma warning restore 612, 618
        }
    }
}
